name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.4.6
  coverage: ^1.6.4
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  test: ^1.24.8
  very_good_analysis: ^5.1.0
